# CI
name: CI Pipeline

# This action will trigger on every pull request get created
on:
    pull_request:
        types:
            - opened
            - synchronize

# Job will run on a ubuntu instance
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code
            - uses: actions/checkout@v3
            # Setup node with version 16
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            # Install project packages
            - run: npm install
            # Execute tests
            - run: npm run test
            # Build the package
            - run: npm run build
